// This file is dynamically generated by STI-Launcher.ps1
// Do not edit manually.
window.NS_METADATA = {
    user: 'Desconocido',
    hostname: 'Terminal-Local',
    status: 'No detectado'
};
